[package]
name = "oalm"
version = "0.1.0"
authors = ["Rached Mejri <rachedmejri74100@gmail.com>"]

[dependencies]
reqwest = "0.9.5"
clap =  "~2.27.0"
git2 = "0.7"
zip = "0.5.0"
tempfile = "3.0.5"
dirs = "1.0"
username = "0.2.0"